# Dependabot configuration file for keeping dependencies up-to-date ğŸ› ï¸
version: 2

updates:
    # NPM packages updates ğŸŒ
    - package-ecosystem: 'npm' # ğŸ› ï¸ Node.js package ecosystem
      directory: '/' # ğŸ“ Location of package manifests (package.json)
      schedule:
          interval: 'weekly' # â° Frequency of updates
      allow:
          - dependency-type: 'all' # ğŸ‘¥ Update all types of dependencies (direct and development)

    # GitHub Actions updates ğŸš€
    - package-ecosystem: 'github-actions' # ğŸš€ GitHub Actions ecosystem
      directory: '/' # ğŸ“ Location of GitHub Actions workflows
      schedule:
          interval: 'weekly' # â° Frequency of updates
      allow:
          - dependency-type: 'all' # ğŸ‘¥ Update all types of dependencies (direct and development)
